version: '2'
services:
    codedevstuff-app:
        image: codedevstuff
        external_links:
            - codedevstuff-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/codedevstuff
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    codedevstuff-postgresql:
        extends:
            file: postgresql.yml
            service: codedevstuff-postgresql
